name: readme-scribe

on:
  schedule:
    - cron: "0 0 */1 * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  readme-scribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: muesli/readme-scribe@master
        with:
          template: templates/README.md.tpl
          writeTo: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update generated README"
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
